config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#index'

  resources :blog, only: %w[index show] do
    collection do
      resources :category, only: :show, to: 'blog#category'
      resources :tag, only: :show, to: 'blog#tag'
      get 'search', to: 'blog#search'
    end
  end

  get '/:page_type/:slug/', to: 'pages#index'

  # No route matched
  get '/*a', to: 'pages#not_found'
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  before_action :menu_items, :categories

  def index
    @page_data = OpenStruct.new(seo: OpenStruct.new(title: 'Sample Blog - All Posts',
                                                    description: 'Sample blog powered by ButterCMS, showing all posts.'),
                                breadcrumbs: helpers.breadcrumbs(title: 'All Blog Posts', crumbs: [
                                                           { title: 'Home', url: root_path },
                                                           { title: 'All Blog Posts', url: nil }
                                                         ]))
    @posts = butter_posts
  end

  def category
    @category = @categories.find { |cat| cat.slug == params[:id] }
    raise ButterCmsError::ResourceNotFound, "Category \"#{params[:id]}\" was not found in Butter CMS API" if @category.blank?

    @posts = butter_posts({ "category_slug": params[:id] })
    @page_data = OpenStruct.new(seo: OpenStruct.new(title: "Sample Blog - category: #{@category.name}",
                                                    description: "Sample blog powered by ButterCMS, showing category: #{@category.name}."),
                                breadcrumbs: helpers.breadcrumbs(title: 'Blog Posts by Category', crumbs: [
                                                           { title: 'Home', url: root_path },
                                                           { title: 'Blog', url: blog_index_path },
                                                           { title: "Category: #{@category.name}", url: nil }
                                                         ]))
    render 'blog/index'
  end

  def tag
    @tags = butter_tags
    @tag = @tags.find { |tag| tag.slug == params[:id] }
    raise ButterCmsError::ResourceNotFound, "Tag \"#{params[:id]}\" was not found in Butter CMS API" if @tag.blank?

    @posts = butter_posts({ "tag_slug": params[:id] })
    @page_data = OpenStruct.new(seo: OpenStruct.new(title: "Sample Blog - tag: #{@tag.name}",
                                                    description: "Sample blog powered by ButterCMS, showing tag: #{@tag.name}."),
                                breadcrumbs: helpers.breadcrumbs(title: 'Blog Posts by Tag', crumbs: [
                                                           { title: 'Home', url: root_path },
                                                           { title: 'Blog', url: blog_index_path },
                                                           { title: "Tag: #{@tag.name}", url: nil }
                                                         ]))
    render 'blog/index'
  end

  def search
    @posts = butter_search
    @page_data = OpenStruct.new(seo: OpenStruct.new(title: "Sample Blog - search results for #{params[:q]}",
                                                    description: "Sample blog powered by ButterCMS, showing search results for query: \"#{params[:q]}\""),
                                breadcrumbs: helpers.breadcrumbs(title: 'Search Results', crumbs: [
                                                           { title: 'Home', url: root_path },
                                                           { title: 'Blog', url: blog_index_path },
                                                           { title: "Search: #{params[:q]}", url: nil }
                                                         ]))
    render 'blog/index'
  end

  def show
    @post = butter_post(params[:id])
    @page_data = OpenStruct.new(seo: OpenStruct.new(title: @post.seo_title,
                                                    description: @post.meta_description,
                                                    featured_image: @post.featured_image),
                                breadcrumbs: helpers.breadcrumbs(title: @post.title, crumbs: [
                                                           { title: 'Home', url: root_path },
                                                           { title: 'Blog', url: blog_index_path },
                                                           { title: @post.title, url: nil }
                                                         ]))
  end

  private

  def categories
    @categories ||= butter_categories
  end

  def menu_items
    @menu_items ||= butter_collection(['navigation_menu_item']).navigation_menu_item
  end
end

app/views/blog/_blog_roll_cards.html.erb
<div class="col-12 col-lg-8 blog-roll-cards">
  <div class="row"><!--nested row for blogroll-->
    <% if posts.items.blank? %>
      <h3>No blog posts found matching this query.</h3>
    <% else %>
      <% posts.each do |post| %>
        <%= render partial: 'blog/single_post_card', locals: { post: post } %>
      <% end %>
    <% end%>
  </div>
</div>

app/views/blog/_breadcrumbs.html.erb
<h2><%= breadcrumbs.title %></h2>
<ul class="breadcrumb-nav">
  <% breadcrumbs.crumbs.each do |c| %>
    <li><a href="<%= c.url.present? ? c.url : "javascript:void(0)" %>"><%= c.title %></a></li>
  <% end %>
</ul>

app/views/blog/_categories_widget.html.erb
<div class="widget categories-widget">
  <h5 class="widget-title">Categories</h5>
  <ul class="categories-list">
    <% categories.each do |category| %>
      <li>
        <a href="<%= category_path(category.slug) %>"><%= category.name %></a>
      </li>
    <% end %>
  </ul>
</div>

app/views/blog/_search_widget.html.erb
<div class="sidebar blog-grid-page">
  <div class="widget search-widget">
    <h5 class="widget-title">Search This Site</h5>
    <form action="<%= search_blog_index_path %>">
      <input name="q" type="text" placeholder="Search Here...">
      <button type="submit"><i class="lni lni-search-alt"></i></button>
    </form>
  </div>
</div>

app/views/blog/_single_post.html.erb
<% if post.present? %>
  <div class="single-post">
    <div class="single-post-meta">
      <h2 class="single-post-header"><%= post.title %></h2>
      <ul class="single-post-meta-info">
        <li>
          <a href="javascript:void(0)">
            <img src="<%= post.author.profile_image.present? ? post.author.profile_image : "assets/images/team/team-1.png" %>"
                                                  alt="#"><%= post.author.first_name + " " + post.author.last_name %>
          </a>
        </li>
        <li>
          <a href="javascript:void(0)"><i class="lni lni-calendar"></i> <%= DateTime.parse(post.published).strftime("%d %b %Y") %>
          </a>
        </li>
        <% post.tags.each do |tag| %>
          <li>
            <a href="<%= tag_path(tag.slug) %>"><i class="lni lni-tag"></i> <%= tag.name %></a>
          </li>
        <% end %>
      </ul>
    </div>
    <% if post.featured_image.present? %>
      <div class="single-post-thumbnail">
        <img src="<%= post.featured_image %>" alt="">
      </div>
    <% end %>
    <div class="single-post-body">
      <%= post.body.html_safe %>
    </div>
  </div>
<% else %>
  <h2>Blog Post Not Found</h2>
<% end %>

app/views/blog/_single_post_card.html.erb
<div class="col-12 col-lg-6">
  <div class="blog-roll-card">
    <div class="blog-roll-card-meta">
      <h2 class="blog-roll-card-header"><a href="<%= blog_path(post.slug) %>"><%= post.title %></a></h2>
      <ul class="blog-roll-card-meta-info">
        <li>
          <a href="javascript:void(0)"><img src="<%= post.author.profile_image.present? ? post.author.profile_image : "/assets/images/team/team-1.png" %>" alt="#"><%= post.author.first_name + " " + post.author.last_name %></a>
        </li>
        <li>
          <a href="javascript:void(0)"><i class="lni lni-calendar"></i> <%= DateTime.parse(post.published).strftime("%d %b %Y") %>
          </a>
        </li>
        <% post.tags.each do |tag| %>
          <li>
            <a href="<%= tag_path(tag.slug) %>"><i class="lni lni-tag"></i> <%= tag.name %></a>
          </li>
        <% end %>
      </ul>
    </div>
    <% if post.featured_image.present? %>
      <div class="single-post-thumbnail">
        <img src="<%= post.featured_image %>" alt="<%= post.featured_image_alt %>">
      </div>
    <% end %>
    <div class="blog-roll-card-body">
      <p><%= post.summary %></p>
    </div>
    <div class="blog-roll-card-footer text-center">
      <a href="<%= blog_path(post.slug) %>" class="main-btn btn-hover">Read More</a>
    </div>
  </div>
</div>

app/views/blog/index.html.erb
<section id="blog-roll" class="blog-roll-nav">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="section-title text-center">
          <h2><%= @page_data.breadcrumbs.title %></h2>
          <ul class="breadcrumb-nav">
            <% @page_data.breadcrumbs.crumbs.each do |c| %>
              <li><a href="<%= c.url.present? ? c.url : "javascript:void(0)" %>"><%= c.title %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="blog-posts">
  <div class="container">
    <div class="row justify-content-center">
      <!-- Blog Posts -->
      <%= render partial: 'blog_roll_cards', locals: { posts: @posts } %>
      <!-- Widgets Column -->
      <aside class="col-12 col-lg-4">
        <%= render partial: 'search_widget' %>
        <%= render partial: 'categories_widget', locals: { categories: @categories } %>
      </aside>
    </div>
  </div>
</section>

app/views/blog/show.html.erb
<section id="blog-header" class="single-post-nav">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="section-title text-center">
          <%= render partial: 'breadcrumbs', locals: { breadcrumbs: @page_data.breadcrumbs } %>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="blog-post">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-12 col-12">
        <%= render partial: 'single_post', locals: { post: @post } %>
      </div>
      <aside class="col-lg-4 col-md-12 col-12">
        <%= render partial: 'search_widget' %>
        <%= render partial: 'categories_widget', locals: { categories: @categories } %>
      </aside>
    </div>
  </div>
</section>